import type { RedisClient } from '@devvit/public-api'
import { Keys } from '../redis/keys.js'

// ─── Response types ────────────────────────────────────────────────────────────

export interface AIGCResult {
  score: number
  heuristics: [string, string, string]
}

export interface AppealResult {
  summary: string
  riskLevel: 'low' | 'medium' | 'high'
  riskReason: string
}

export interface EditResult {
  intent: 'evasion' | 'cosmetic' | 'unclear'
  confidence: number
  reason: string
}

// ─── Core Gemini fetch (with retry) ───────────────────────────────────────────

async function callGemini<T>(prompt: string, apiKey: string, retries = 2): Promise<T> {
  let lastError: Error | undefined
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      console.log(`[Gemini] Attempt ${attempt + 1}/${retries + 1}`)
      const res = await fetch(
        'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: 'gemini-1.5-flash',
            messages: [{ role: 'user', content: prompt }],
            response_format: { type: 'json_object' },
          }),
        }
      )
      if (!res.ok) {
        const errBody = await res.text()
        console.error(`[Gemini] HTTP ${res.status}: ${errBody.slice(0, 500)}`)
        throw new Error(`Gemini HTTP ${res.status}: ${errBody.slice(0, 200)}`)
      }
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const data = (await res.json()) as any
      const rawContent = data?.choices?.[0]?.message?.content ?? ''
      console.log(`[Gemini] Raw response (first 300 chars): ${rawContent.slice(0, 300)}`)
      // Strip markdown fences if present (some models wrap JSON in ```json ... ```)
      const cleaned = rawContent.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim()
      return JSON.parse(cleaned) as T
    } catch (err) {
      lastError = err instanceof Error ? err : new Error(String(err))
      console.error(`[Gemini] Attempt ${attempt + 1} failed: ${lastError.message}`)
      if (attempt < retries) await sleep(500 * 2 ** attempt)
    }
  }
  throw lastError
}

function sleep(ms: number) {
  return new Promise<void>((r) => setTimeout(r, ms))
}

function hashContent(text: string): string {
  let h = 0x811c9dc5
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i)
    h = (h * 0x01000193) >>> 0
  }
  return h.toString(16)
}

function ttl(seconds: number): { expiration: Date } {
  return { expiration: new Date(Date.now() + seconds * 1000) }
}

// ─── Prompt 1 — AIGC Classifier ───────────────────────────────────────────────

const AIGC_PROMPT = (content: string) => `
You are a Reddit moderation assistant. Analyze the following post/comment and determine the likelihood it was generated by AI.

Return ONLY a JSON object, no other text:
{
  "score": <number 0-100>,
  "heuristics": [<string>, <string>, <string>]
}

Score guide: 0 = definitely human, 100 = definitely AI-generated.
Heuristics: cite exactly 3 specific signals (e.g. "verbose meandering paragraphs", "heavy em-dash usage", "no personal anecdote or specific detail").

Content to analyze:
"""
${content}
"""
`

export async function scoreContent(
  content: string,
  redis: RedisClient,
  apiKey: string
): Promise<AIGCResult> {
  const hash = hashContent(content)
  const cacheKey = Keys.aiScore('aigc:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as AIGCResult

  const result = await callGemini<AIGCResult>(AIGC_PROMPT(content), apiKey)
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}

// ─── Prompt 2 — Appeal Summarizer ─────────────────────────────────────────────

const APPEAL_PROMPT = (
  banReason: string,
  accountAge: number,
  karma: number,
  formAnswers: string
) => `
You are helping a Reddit moderator evaluate a ban appeal. Summarize this appeal objectively and assess risk.

Return ONLY a JSON object:
{
  "summary": "<2 sentences, neutral tone>",
  "riskLevel": "low|medium|high",
  "riskReason": "<one sentence explaining risk level>"
}

Ban reason: ${banReason}
Account age: ${accountAge} days
Account karma: ${karma}
User's appeal answers:
${formAnswers}
`

export async function summarizeAppeal(
  banReason: string,
  accountAge: number,
  karma: number,
  formAnswers: string,
  redis: RedisClient,
  apiKey: string
): Promise<AppealResult> {
  const hash = hashContent(`${banReason}|${formAnswers}`)
  const cacheKey = Keys.aiScore('appeal:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as AppealResult

  const result = await callGemini<AppealResult>(
    APPEAL_PROMPT(banReason, accountAge, karma, formAnswers),
    apiKey
  )
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}

// ─── Prompt 3 — Edit Intent Classifier ───────────────────────────────────────

const EDIT_PROMPT = (original: string, edited: string, deltaMinutes: number) => `
A Reddit user edited their post/comment. Determine if the edit was to evade moderation.

Return ONLY a JSON object:
{
  "intent": "evasion|cosmetic|unclear",
  "confidence": <number 0-100>,
  "reason": "<one sentence>"
}

Original content: """${original}"""
Edited content: """${edited}"""
Time between report and edit: ${deltaMinutes} minutes
`

export async function classifyEdit(
  original: string,
  edited: string,
  deltaMinutes: number,
  redis: RedisClient,
  apiKey: string
): Promise<EditResult> {
  const hash = hashContent(`${original}|${edited}`)
  const cacheKey = Keys.aiScore('edit:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as EditResult

  const result = await callGemini<EditResult>(
    EDIT_PROMPT(original, edited, deltaMinutes),
    apiKey
  )
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}
