import type { RedisClient } from '@devvit/public-api'
import { Keys } from '../redis/keys.js'

// ─── Response types ────────────────────────────────────────────────────────────

export interface AIGCResult {
  score: number
  heuristics: [string, string, string]
}

export interface AppealResult {
  summary: string
  riskLevel: 'low' | 'medium' | 'high'
  riskReason: string
}

export interface EditResult {
  intent: 'evasion' | 'cosmetic' | 'unclear'
  confidence: number
  reason: string
}

export interface CopilotResult {
  action: 'approve' | 'remove' | 'ban' | 'escalate'
  confidence: 'high' | 'medium' | 'low'
  reason: string
  draftMessage: string
  banReason?: string
  banDuration?: number
}

export interface DossierSummaryResult {
  summary: string
  riskTag: 'low' | 'medium' | 'high'
}

export interface DossierSummarySignals {
  username: string
  accountAgeDays: number | null
  karma: number | null
  recentItemCount: number
  removedCount: number
  evasionCount: number
  appealStatus: string | null
  recentTitles: string[] // first ~5 titles to give Gemini flavor
}

export interface CopilotSignals {
  subName: string
  title: string
  body: string
  author: string
  accountAgeDays: number
  authorKarma: number | null
  aigcScore: number | null
  aigcHeuristics: string[]
  reportCount: number
  reportReasons: string[]
  removalCount30d: number
  totalItems30d: number
  evasionCount: number
  prevAppealStatus: string | null
  itemAgeHours: number
}

// ─── Core Gemini fetch (with retry) ───────────────────────────────────────────

async function callGemini<T>(prompt: string, apiKey: string, retries = 1): Promise<T> {
  let lastError: Error | undefined
  for (let attempt = 0; attempt <= retries; attempt++) {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 10000)
    try {
      console.log(`[Gemini] Attempt ${attempt + 1}/${retries + 1}`)
      const res = await fetch(
        'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: 'gemini-2.5-flash',
            messages: [{ role: 'user', content: prompt }],
            response_format: { type: 'json_object' },
          }),
          signal: controller.signal,
        }
      )
      clearTimeout(timeout)
      if (!res.ok) {
        const errBody = await res.text()
        console.error(`[Gemini] HTTP ${res.status}: ${errBody.slice(0, 500)}`)
        throw new Error(`Gemini HTTP ${res.status}: ${errBody.slice(0, 200)}`)
      }
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const data = (await res.json()) as any
      const rawContent = data?.choices?.[0]?.message?.content ?? ''
      console.log(`[Gemini] Raw response (first 300 chars): ${rawContent.slice(0, 300)}`)
      // Strip markdown fences if present (some models wrap JSON in ```json ... ```)
      const cleaned = rawContent.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim()
      return JSON.parse(cleaned) as T
    } catch (err) {
      clearTimeout(timeout)
      lastError = err instanceof Error ? err : new Error(String(err))
      console.error(`[Gemini] Attempt ${attempt + 1} failed: ${lastError.message}`)
      if (attempt < retries) await sleep(500 * 2 ** attempt)
    }
  }
  throw lastError
}

function sleep(ms: number) {
  return new Promise<void>((r) => setTimeout(r, ms))
}

function hashContent(text: string): string {
  let h = 0x811c9dc5
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i)
    h = (h * 0x01000193) >>> 0
  }
  return h.toString(16)
}

function ttl(seconds: number): { expiration: Date } {
  return { expiration: new Date(Date.now() + seconds * 1000) }
}

// ─── Prompt 1 — AIGC Classifier ───────────────────────────────────────────────

const AIGC_PROMPT = (content: string) => `
You are a Reddit moderation assistant. Analyze the following post/comment and determine the likelihood it was generated by AI.

Return ONLY a JSON object, no other text:
{
  "score": <number 0-100>,
  "heuristics": [<string>, <string>, <string>]
}

Score guide: 0 = definitely human, 100 = definitely AI-generated.
Heuristics: cite exactly 3 specific signals (e.g. "verbose meandering paragraphs", "heavy em-dash usage", "no personal anecdote or specific detail").

Content to analyze:
"""
${content}
"""
`

export async function scoreContent(
  content: string,
  redis: RedisClient,
  apiKey: string
): Promise<AIGCResult> {
  const hash = hashContent(content)
  const cacheKey = Keys.aiScore('aigc:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as AIGCResult

  const result = await callGemini<AIGCResult>(AIGC_PROMPT(content), apiKey)
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}

// ─── Prompt 2 — Appeal Summarizer ─────────────────────────────────────────────

const APPEAL_PROMPT = (
  banReason: string,
  accountAge: number,
  karma: number,
  formAnswers: string
) => `
You are helping a Reddit moderator evaluate a ban appeal. Summarize this appeal objectively and assess risk.

Return ONLY a JSON object:
{
  "summary": "<2 sentences, neutral tone>",
  "riskLevel": "low|medium|high",
  "riskReason": "<one sentence explaining risk level>"
}

Ban reason: ${banReason}
Account age: ${accountAge} days
Account karma: ${karma}
User's appeal answers:
${formAnswers}
`

export async function summarizeAppeal(
  banReason: string,
  accountAge: number,
  karma: number,
  formAnswers: string,
  redis: RedisClient,
  apiKey: string
): Promise<AppealResult> {
  const hash = hashContent(`${banReason}|${formAnswers}`)
  const cacheKey = Keys.aiScore('appeal:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as AppealResult

  const result = await callGemini<AppealResult>(
    APPEAL_PROMPT(banReason, accountAge, karma, formAnswers),
    apiKey
  )
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}

// ─── Prompt 3 — Edit Intent Classifier ───────────────────────────────────────

const EDIT_PROMPT = (original: string, edited: string, deltaMinutes: number) => `
A Reddit user edited their post/comment. Determine if the edit was to evade moderation.

Return ONLY a JSON object:
{
  "intent": "evasion|cosmetic|unclear",
  "confidence": <number 0-100>,
  "reason": "<one sentence>"
}

Original content: """${original}"""
Edited content: """${edited}"""
Time between report and edit: ${deltaMinutes} minutes
`

export async function classifyEdit(
  original: string,
  edited: string,
  deltaMinutes: number,
  redis: RedisClient,
  apiKey: string
): Promise<EditResult> {
  const hash = hashContent(`${original}|${edited}`)
  const cacheKey = Keys.aiScore('edit:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as EditResult

  const result = await callGemini<EditResult>(
    EDIT_PROMPT(original, edited, deltaMinutes),
    apiKey
  )
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}

// ─── Prompt 4 — Mod Copilot ──────────────────────────────────────────────────

const COPILOT_PROMPT = (s: CopilotSignals) => `
You are an expert Reddit moderation assistant for the subreddit "${s.subName}".
Given the post and the signals below, recommend ONE action and explain in one short sentence.

Action choices:
- "approve"   — content is acceptable; clear the report and unflag.
- "remove"    — content violates norms; remove without ban.
- "ban"       — repeat or severe offender; remove and ban the author.
- "escalate"  — signals contradict (e.g. high AI score but clean history); needs human judgment.

Confidence: "high" only when signals strongly converge; "medium" when most agree; "low" when sparse or conflicting.

draftMessage: 1-3 sentences the mod could post as the public removal reason or modmail message. Empathetic, specific, cite the rule pattern (not a rule number, you don't know them). For "approve" return empty string.

If action is "ban": include banReason (mod-facing, short) and banDuration in DAYS (7 default; 30 for repeat; omit for permanent if egregious).

Return ONLY a JSON object, no markdown, no prose:
{
  "action": "approve|remove|ban|escalate",
  "confidence": "high|medium|low",
  "reason": "<one sentence citing the strongest 2-3 signals>",
  "draftMessage": "<empty for approve, else 1-3 sentences>",
  "banReason": "<only if action=ban>",
  "banDuration": <only if action=ban, integer days or omit for permanent>
}

POST
title: ${s.title}
body: ${s.body.slice(0, 1500)}
author: u/${s.author} (account age ${s.accountAgeDays}d, sub karma ${s.authorKarma ?? 'unknown'})
posted: ${s.itemAgeHours}h ago

SIGNALS
- AIGC score: ${s.aigcScore ?? 'not scored'}/100${s.aigcHeuristics.length ? ' (' + s.aigcHeuristics.join('; ') + ')' : ''}
- Reports: ${s.reportCount}${s.reportReasons.length ? ' (' + s.reportReasons.join('; ') + ')' : ''}
- Author's removal rate here (30d): ${s.totalItems30d > 0 ? Math.round((s.removalCount30d / s.totalItems30d) * 100) : 0}% (${s.removalCount30d}/${s.totalItems30d})
- Edit Watch evasion history: ${s.evasionCount > 0 ? s.evasionCount + ' prior evasion edits' : 'none'}
- Prior appeal: ${s.prevAppealStatus ?? 'none'}
`

export async function copilotRecommend(
  signals: CopilotSignals,
  redis: RedisClient,
  apiKey: string
): Promise<CopilotResult> {
  // Hash on the dynamic signals only (not subName/title prefix) so identical situations share cache
  const hash = hashContent(
    `${signals.author}|${signals.aigcScore}|${signals.reportCount}|${signals.removalCount30d}|${signals.evasionCount}|${signals.body.slice(0, 500)}`
  )
  const cacheKey = Keys.aiScore('copilot:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as CopilotResult

  const result = await callGemini<CopilotResult>(COPILOT_PROMPT(signals), apiKey)
  // Validate
  if (!['approve', 'remove', 'ban', 'escalate'].includes(result.action)) {
    result.action = 'escalate'
    result.confidence = 'low'
  }
  if (!['high', 'medium', 'low'].includes(result.confidence)) {
    result.confidence = 'low'
  }
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}

// ─── Prompt 5 — Dossier behavioral summary ─────────────────────────────────

const DOSSIER_SUMMARY_PROMPT = (s: DossierSummarySignals) => `
You are an expert Reddit moderation assistant. Given the user's footprint in this subreddit, write a SHORT behavioral summary (≤25 words) and assign a risk tag.

Risk tag:
- "low"     — clean recent history, no patterns of concern
- "medium"  — mixed signals, some flags worth watching
- "high"    — clear pattern of rule-skirting behavior (evasion edits, high removal rate, etc.)

Tone: neutral, factual, concrete. Mention the strongest 1-2 signals. NOT a value judgment.

Return ONLY a JSON object:
{
  "summary": "<one sentence ≤25 words>",
  "riskTag": "low|medium|high"
}

USER FOOTPRINT
- username: u/${s.username}
- account age: ${s.accountAgeDays ?? 'unknown'} days
- karma: ${s.karma ?? 'unknown'}
- tracked items in this sub: ${s.recentItemCount}
- mod removals against this user: ${s.removedCount}
- edit-evasion incidents flagged: ${s.evasionCount}
- prior appeal: ${s.appealStatus ?? 'none'}
- recent titles: ${s.recentTitles.slice(0, 5).map((t) => `"${t.slice(0, 80)}"`).join('; ') || 'n/a'}
`

// ─── Prompt 6 — Copilot Chat (multi-turn) ─────────────────────────────────

export interface CopilotChatTurn {
  role: 'user' | 'assistant'
  content: string
}

export interface CopilotChatReply {
  content: string
  suggestions: string[] // up to 3 follow-up questions the mod can click
  kind?: 'draft' | 'answer'
}

// Detects mod slash-commands and rewrites them into a directive instruction
// the model executes within the same item context. Keeps history clean.
export function rewriteSlashCommand(userInput: string): { rewritten: string; isDraft: boolean } {
  const trimmed = userInput.trim()
  const lower = trimmed.toLowerCase()
  if (lower.startsWith('/removal-reason') || lower.startsWith('/removal')) {
    const extra = trimmed.replace(/^\/removal[a-z-]*\s*/i, '').trim()
    return {
      rewritten: `Draft a public removal-reason comment for this item, written in the subreddit's voice. Empathetic, specific, name the rule pattern (not a rule number). 1-3 sentences.${extra ? ' Extra context from the mod: ' + extra : ''}`,
      isDraft: true,
    }
  }
  if (lower.startsWith('/modmail')) {
    const extra = trimmed.replace(/^\/modmail\s*/i, '').trim()
    return {
      rewritten: `Draft a modmail reply to the user about this item. Tone: professional, neutral, brief (2-4 sentences). Address their likely concern.${extra ? ' Extra context: ' + extra : ''}`,
      isDraft: true,
    }
  }
  if (lower.startsWith('/sticky')) {
    const extra = trimmed.replace(/^\/sticky\s*/i, '').trim()
    return {
      rewritten: `Draft a sticky-comment mods can pin under this post to explain a controversial decision. Tone: calm, transparent, 2-4 sentences.${extra ? ' Extra context: ' + extra : ''}`,
      isDraft: true,
    }
  }
  if (lower.startsWith('/rule-cite') || lower.startsWith('/rule')) {
    const extra = trimmed.replace(/^\/rule[a-z-]*\s*/i, '').trim()
    return {
      rewritten: `Explain which sub rule pattern this item most likely violates (or doesn't). Cite the pattern in plain language, not a number. 1-2 sentences.${extra ? ' Extra context: ' + extra : ''}`,
      isDraft: false,
    }
  }
  return { rewritten: trimmed, isDraft: false }
}

const COPILOT_CHAT_SYSTEM = (s: CopilotSignals) => `You are Mod Copilot, an AI assistant helping a Reddit moderator of "${s.subName}" investigate one specific item. You have already given a verdict on this item; the mod is now asking follow-up questions.

ITEM CONTEXT
- title: ${s.title}
- body: ${s.body.slice(0, 1500)}
- author: u/${s.author} (account age ${s.accountAgeDays}d, sub karma ${s.authorKarma ?? 'unknown'})
- posted: ${s.itemAgeHours}h ago
- AIGC score: ${s.aigcScore ?? 'not scored'}/100${s.aigcHeuristics.length ? ' (' + s.aigcHeuristics.join('; ') + ')' : ''}
- Reports: ${s.reportCount}${s.reportReasons.length ? ' (' + s.reportReasons.join('; ') + ')' : ''}
- Author's removal rate here (30d): ${s.totalItems30d > 0 ? Math.round((s.removalCount30d / s.totalItems30d) * 100) : 0}% (${s.removalCount30d}/${s.totalItems30d})
- Edit Watch evasion history: ${s.evasionCount > 0 ? s.evasionCount + ' prior evasion edits' : 'none'}
- Prior appeal: ${s.prevAppealStatus ?? 'none'}

RULES
- Be CONCISE. Most answers are 1-3 sentences. Draft messages may be longer if requested.
- Ground every claim in the item context or the signals above. Don't invent facts.
- If asked to draft something, write it as if the mod would paste it directly — no preamble like "Here's a draft:".
- Always end your JSON with 2-3 short follow-up suggestions the mod might want to ask next, tailored to where the conversation is going.

Return ONLY a JSON object, no markdown, no prose outside JSON:
{
  "content": "<your reply, 1-5 sentences unless drafting>",
  "suggestions": ["<question 1>", "<question 2>", "<question 3>"]
}
`

export async function copilotChat(
  signals: CopilotSignals,
  history: CopilotChatTurn[],
  userMessage: string,
  apiKey: string
): Promise<CopilotChatReply> {
  // Build conversation messages array for Gemini chat completions.
  const messages: Array<{ role: string; content: string }> = [
    { role: 'system', content: COPILOT_CHAT_SYSTEM(signals) },
    ...history.map((h) => ({ role: h.role, content: h.content })),
    { role: 'user', content: userMessage },
  ]
  const body = JSON.stringify({
    model: 'gemini-2.5-flash',
    messages,
    response_format: { type: 'json_object' },
  })

  // Retry once on transient Gemini errors (503 UNAVAILABLE during traffic
  // spikes, 429 rate-limit). 800ms delay between attempts.
  let lastErr: Error | undefined
  for (let attempt = 0; attempt < 2; attempt++) {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 15000)
    try {
      console.log(`[Gemini] copilotChat turn=${history.length + 1} attempt=${attempt + 1}`)
      const res = await fetch(
        'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
          body,
          signal: controller.signal,
        }
      )
      clearTimeout(timeout)
      if (!res.ok) {
        const errBody = await res.text()
        const transient = res.status === 503 || res.status === 429
        const message = `Gemini HTTP ${res.status}: ${errBody.slice(0, 200)}`
        if (transient && attempt === 0) {
          console.log(`[Gemini] transient ${res.status}, will retry in 800ms`)
          lastErr = new Error(message)
          await sleep(800)
          continue
        }
        throw new Error(message)
      }
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const data = (await res.json()) as any
      const rawContent = data?.choices?.[0]?.message?.content ?? ''
      const cleaned = rawContent.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim()
      const parsed = JSON.parse(cleaned) as CopilotChatReply
      if (typeof parsed.content !== 'string' || parsed.content.length === 0) {
        throw new Error('Chat reply had empty content')
      }
      if (!Array.isArray(parsed.suggestions)) parsed.suggestions = []
      parsed.suggestions = parsed.suggestions.filter((s) => typeof s === 'string' && s.length > 0).slice(0, 3)
      return parsed
    } catch (err) {
      clearTimeout(timeout)
      lastErr = err instanceof Error ? err : new Error(String(err))
      // Only retry on the first attempt; bail on the second.
      if (attempt === 0 && /HTTP (503|429)/.test(lastErr.message)) {
        await sleep(800)
        continue
      }
      throw lastErr
    }
  }
  throw lastErr ?? new Error('copilotChat: exhausted retries')
}

export async function dossierSummary(
  signals: DossierSummarySignals,
  redis: RedisClient,
  apiKey: string
): Promise<DossierSummaryResult> {
  const hash = hashContent(
    `${signals.username}|${signals.accountAgeDays}|${signals.recentItemCount}|${signals.removedCount}|${signals.evasionCount}|${signals.appealStatus}`
  )
  const cacheKey = Keys.aiScore('dossier:' + hash)

  const cached = await redis.get(cacheKey)
  if (cached) return JSON.parse(cached) as DossierSummaryResult

  const result = await callGemini<DossierSummaryResult>(DOSSIER_SUMMARY_PROMPT(signals), apiKey)
  if (!['low', 'medium', 'high'].includes(result.riskTag)) {
    result.riskTag = 'low'
  }
  if (typeof result.summary !== 'string' || result.summary.length === 0) {
    result.summary = 'No notable behavioral signals.'
    result.riskTag = 'low'
  }
  await redis.set(cacheKey, JSON.stringify(result), ttl(86400))
  return result
}
